#docker run -p 127.0.0.1:9042:9042 -p 127.0.0.1:9160:9160 -d cassandra
#docker-compose -f "docker-cassandra.yml" up -d
version: '2'
services:
  cassandra:
    image: cassandra
    container_name: cassandra
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
    restart: unless-stopped